# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progenitor', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', '-- select --'), ('f', 'Female'), ('m', 'Male')], max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
